# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"data": "01_model.ipynb",
         "test_data": "01_model.ipynb",
         "TIME_INTERVALS": "01_model.ipynb",
         "SHOW_SUMMARY": "01_model.ipynb",
         "INPUT_SHAPE": "01_model.ipynb",
         "EPOCHS": "01_model.ipynb",
         "BATCH_SIZE": "01_model.ipynb",
         "MASK_PERCENTAGE": "01_model.ipynb",
         "EPSILON": "01_model.ipynb",
         "ALPHA": "01_model.ipynb",
         "CHECKPOINT": "01_model.ipynb",
         "SAVED_IMAGES": "01_model.ipynb",
         "discriminator_loss": "01_model.ipynb",
         "ConvolutionBlock": "01_model.ipynb",
         "discriminator": "01_model.ipynb",
         "generator_loss": "01_model.ipynb",
         "GeneratorConvolutionBlock": "01_model.ipynb",
         "generator": "01_model.ipynb",
         "mask_width": "01_model.ipynb",
         "get_masked_images": "01_model.ipynb",
         "get_demask_images": "01_model.ipynb",
         "train_step": "01_model.ipynb",
         "train": "01_model.ipynb",
         "generate_and_save_images": "01_model.ipynb",
         "d_input_shape": "01_model.ipynb",
         "d_dropout": "01_model.ipynb",
         "discriminator_optimizer": "01_model.ipynb",
         "disc_model": "01_model.ipynb",
         "g_input_shape": "01_model.ipynb",
         "generator_optimizer": "01_model.ipynb",
         "gen_model": "01_model.ipynb",
         "image": "01_model.ipynb",
         "disc_model.trainable": "01_model.ipynb",
         "generated_img": "01_model.ipynb",
         "conf_generated_img": "01_model.ipynb",
         "combined": "01_model.ipynb"}

modules = ["models.py"]

doc_url = "https://wprazuch.github.io/outpainting/"

git_url = "https://github.com/wprazuch/outpainting/tree/main/"

def custom_doc_links(name): return None
